### PR TITLE
CRAYSAT-1884: Updating cray-product-catalog & csm-api-client to latest versions

### PR DESCRIPTION
**Pull request by shivaprasad-metimath**
## Summary and Scope

Updating cray-product-catalog & csm-api-client to latest versions

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CRAYSAT-1884](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1884)

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * Rocket,Gamora,Surtur

### Test description:

Test the below SAT utilities
sat showrev --products
sat bootprep
cfs-config-util

## Risks and Mitigations

Minimal

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [x] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

### CODE REVIEW

**Comment by shivaprasad-metimath** [comment]
Testing was done on surtur,rocket for lower versions than 2.3.1 and for 2.3.1 it was tested on gamora system.
Sat showrev,bootprep were tested along with cfs-config-util.
Below is the link to complete output: https://gist.github.com/shivaprasad-metimath/432dbacecaa4346b011777dc5863ec80

**Review by annapoorna-s-alt — COMMENTED** [review]
Partially you are on track. The code changes looks good to me. But, you have to update new version of  `cray-product-catalog` in [cfs-config-util](https://github.com/Cray-HPE/cfs-config-util) repository, get the new unstable build and test with `cfs-config-util` commands.
Testing `cfs-config-util` commands with this build doesn't make sense to me.

**Comment by shivaprasad-metimath** [comment]
> Partially you are on track. The code changes looks good to me. But, you have to update new version of `cray-product-catalog` in [cfs-config-util](https://github.com/Cray-HPE/cfs-config-util) repository, get the new unstable build and test with `cfs-config-util` commands. Testing `cfs-config-util` commands with this build doesn't make sense to me.

Ok, the testing for cfs-config-util will be done with new unstable build in respective repo. are this repo specific testing satisfactory?
Let me know if any comments, else will proceed with merging this PR and raise a separate one for cfs-config-util repo

**Review by annapoorna-s-alt — APPROVED** [review]
Approving the code changes as testing of related `sat` commands looks good

**Pull request merged**
